### ISSUE TITLE
Sleep in bash caused custom-script stuck and no response to waagent

### ISSUE THREAD

**Issue by hebinhuang** [Azure/custom-script-extension-linux#99] opened 2017-07-20 22:45 UTC
The repro is pretty simple, just add a while loop to sleep. In the stdout of custom-script, I can only see two iteration.
```
echo "1st Loop to sleep"
count=0
while [ $count -le 12 ]; do
    (( count++ ))
    echo "Trying to sleep 30s. nRetries: $count"
    sleep 30
done
```

- /var/log/azure/custom-script/handler.log
```
+ /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/bin/custom-script-extension install
time=2017-07-20T21:03:32Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 event=start
time=2017-07-20T21:03:32Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 status="not reported for operation (by design)"
time=2017-07-20T21:03:32Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 event="created data dir" path=/var/lib/waagent/custom-script
time=2017-07-20T21:03:32Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 event=installed
time=2017-07-20T21:03:32Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 status="not reported for operation (by design)"
time=2017-07-20T21:03:32Z version=v2.0.3/git@f21ef81-clean operation=install seq=0 event=end
Writing a placeholder status file indicating progress before forking: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/status/0.status
+ nohup /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/bin/custom-script-extension enable
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=start
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=pre-check
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="checking for state migration"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="no old state found to migrate"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="comparing seqnum" path=/var/lib/waagent/custom-script/seqnum
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="seqnum saved" path=/var/lib/waagent/custom-script/seqnum
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="reading configuration"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="read configuration"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="validating json schema"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="json schema valid"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="parsing configuration json"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="parsed configuration json"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="validating configuration logically"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="validated configuration"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="creating output directory" path=/var/lib/waagent/custom-script/download/0
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="created output directory"
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 files=4
time=2017-07-20T21:03:33Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 file=0 event="download start"
time=2017-07-20T21:03:34Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 file=0 event="download complete" output=/var/lib/waagent/custom-script/download/0
time=2017-07-20T21:03:34Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 file=1 event="download start"
time=2017-07-20T21:03:34Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 file=1 event="download complete" output=/var/lib/waagent/custom-script/download/0
time=2017-07-20T21:03:34Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 file=2 event="download start"
time=2017-07-20T21:03:34Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 file=2 event="download complete" output=/var/lib/waagent/custom-script/download/0
time=2017-07-20T21:03:34Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 file=3 event="download start"
time=2017-07-20T21:03:34Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 file=3 event="download complete" output=/var/lib/waagent/custom-script/download/0
time=2017-07-20T21:03:34Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="executing command" output=/var/lib/waagent/custom-script/download/0
Not writing a placeholder status file, already exists: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/status/0.status
+ nohup /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/bin/custom-script-extension enable
time=2017-07-20T21:05:24Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=start
time=2017-07-20T21:05:24Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=pre-check
time=2017-07-20T21:05:24Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="checking for state migration"
time=2017-07-20T21:05:24Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="no old state found to migrate"
time=2017-07-20T21:05:24Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="comparing seqnum" path=/var/lib/waagent/custom-script/seqnum
time=2017-07-20T21:05:24Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=exit message="this script configuration is already processed, will not run again"
Not writing a placeholder status file, already exists: /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/status/0.status
+ nohup /var/lib/waagent/Microsoft.Azure.Extensions.CustomScript-2.0.3/bin/custom-script-extension enable
time=2017-07-20T21:33:48Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=start
time=2017-07-20T21:33:48Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=pre-check
time=2017-07-20T21:33:48Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="checking for state migration"
time=2017-07-20T21:33:48Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 message="no old state found to migrate"
time=2017-07-20T21:33:48Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event="comparing seqnum" path=/var/lib/waagent/custom-script/seqnum
time=2017-07-20T21:33:48Z version=v2.0.3/git@f21ef81-clean operation=enable seq=0 event=exit message="this script configuration is already processed, will not run again"
```
- /var/log/waagent.log
```
2017/07/20 21:02:55.622125 INFO Azure Linux Agent Version:2.2.12
2017/07/20 21:02:55.625478 INFO OS: ubuntu 16.04
2017/07/20 21:02:55.628416 INFO Python: 3.5.2
2017/07/20 21:02:55.631582 INFO Run daemon
2017/07/20 21:02:55.634772 INFO No RDMA handler exists for distro='Ubuntu' version='16.04'
2017/07/20 21:02:55.638295 INFO Clean protocol
2017/07/20 21:02:55.640691 INFO Running CloudInit provisioning handler
2017/07/20 21:02:55.646277 INFO Detect protocol endpoints
2017/07/20 21:02:55.649788 INFO Clean protocol
2017/07/20 21:02:55.652779 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/07/20 21:02:55.657115 INFO Test for route to 168.63.129.16
2017/07/20 21:02:55.660523 INFO Route to 168.63.129.16 exists
2017/07/20 21:02:55.664556 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:02:55.682126 INFO Fabric preferred wire protocol version:2015-04-05
2017/07/20 21:02:55.686944 INFO Wire protocol version:2012-11-30
2017/07/20 21:02:55.690267 WARNING Server preferred version:2015-04-05
2017/07/20 21:03:00.173542 INFO ssh host key found at: /etc/ssh/ssh_host_rsa_key.pub
2017/07/20 21:03:00.181031 INFO Thumbprint obtained from : /etc/ssh/ssh_host_rsa_key.pub
2017/07/20 21:03:00.185585 INFO Finished provisioning
2017/07/20 21:03:05.898434 INFO Event: name=WALinuxAgent, op=Provision, message=Provision succeed
2017/07/20 21:03:05.901075 INFO RDMA capabilities are not enabled, skipping
2017/07/20 21:03:05.902417 INFO Installed Agent WALinuxAgent-2.2.12 is the most current agent
2017/07/20 21:03:06.034141 INFO Agent WALinuxAgent-2.2.12 is running as the goal state agent
2017/07/20 21:03:06.037341 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:03:06.042859 INFO Event: name=WALinuxAgent-2.2.12, op=HeartBeat, message=
2017/07/20 21:03:06.045554 INFO Start env monitor service.
2017/07/20 21:03:06.047402 INFO Configure routes
2017/07/20 21:03:06.049107 INFO Gateway:None
2017/07/20 21:03:06.050430 INFO Routes:None
2017/07/20 21:03:06.051541 WARNING Hostname record does not exist, creating [/var/lib/waagent/published_hostname] with hostname [CloudApiDev05]
2017/07/20 21:03:06.060266 INFO WALinuxAgent-2.2.12 running as process 2196
2017/07/20 21:03:06.060561 INFO Set block dev timeout: sda with timeout: 300
2017/07/20 21:03:06.064013 INFO Set block dev timeout: sdb with timeout: 300
2017/07/20 21:03:06.064300 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:03:06.269368 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.10 downloaded successfully
2017/07/20 21:03:06.314317 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.12 downloaded successfully
2017/07/20 21:03:06.350423 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.13 downloaded successfully
2017/07/20 21:03:06.390231 INFO Event: name=WALinuxAgent, op=Install, message=Agent WALinuxAgent-2.2.8 downloaded successfully
2017/07/20 21:03:06.393911 INFO Agent WALinuxAgent-2.2.12 discovered WALinuxAgent-2.2.13 as an update and will exit
2017/07/20 21:03:06.911013 INFO Agent WALinuxAgent-2.2.12 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/07/20 21:03:06.912624 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.12 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/07/20 21:03:06.919507 INFO Determined Agent WALinuxAgent-2.2.13 to be the latest agent
2017/07/20 21:03:07.920526 INFO Agent WALinuxAgent-2.2.13 is running as the goal state agent
2017/07/20 21:03:07.926213 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:03:07.931272 INFO Event: name=WALinuxAgent-2.2.13, op=HeartBeat, message=
2017/07/20 21:03:07.933353 INFO Start env monitor service.
2017/07/20 21:03:07.938166 INFO Configure routes
2017/07/20 21:03:07.941789 INFO Gateway:None
2017/07/20 21:03:07.943214 INFO Routes:None
2017/07/20 21:03:07.950257 INFO WALinuxAgent-2.2.13 running as process 2245
2017/07/20 21:03:07.953222 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:03:07.988378 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:03:08.028739 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/07/20 21:03:29.250116 INFO Incarnation is out of date. Update goalstate.
2017/07/20 21:03:32.345041 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Target handler state: enabled
2017/07/20 21:03:32.346102 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] [Enable] current handler state is: notinstalled
2017/07/20 21:03:32.459928 INFO Event: name=Microsoft.Azure.Extensions.CustomScript, op=Download, message=Download succeeded
2017/07/20 21:03:32.461547 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Initialize extension directory
2017/07/20 21:03:32.462766 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Update settings file: 0.settings
2017/07/20 21:03:32.463650 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Install extension [bin/custom-script-shim install]
2017/07/20 21:03:33.466915 INFO Event: name=Microsoft.Azure.Extensions.CustomScript, op=Install, message=Launch command succeeded: bin/custom-script-shim install
2017/07/20 21:03:33.468861 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Enable extension [bin/custom-script-shim enable]
2017/07/20 21:03:34.473408 INFO Event: name=Microsoft.Azure.Extensions.CustomScript, op=Enable, message=Launch command succeeded: bin/custom-script-shim enable
2017/07/20 21:03:34.507465 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/07/20 21:04:20.497676 INFO Agent WALinuxAgent-2.2.12 forwarding signal 15 to WALinuxAgent-2.2.13
2017/07/20 21:05:19.107450 INFO Azure Linux Agent Version:2.2.14
2017/07/20 21:05:19.108603 INFO OS: ubuntu 16.04
2017/07/20 21:05:19.109216 INFO Python: 3.5.2
2017/07/20 21:05:19.109840 INFO Run daemon
2017/07/20 21:05:19.110477 INFO No RDMA handler exists for distro='Ubuntu' version='16.04'
2017/07/20 21:05:19.111345 INFO Clean protocol
2017/07/20 21:05:19.112051 INFO Provisioning already completed, skipping.
2017/07/20 21:05:19.112720 INFO RDMA capabilities are not enabled, skipping
2017/07/20 21:05:19.115992 INFO Installed Agent WALinuxAgent-2.2.14 is the most current agent
2017/07/20 21:05:19.236747 INFO Agent WALinuxAgent-2.2.14 is running as the goal state agent
2017/07/20 21:05:19.239570 INFO Detect protocol endpoints
2017/07/20 21:05:19.240227 INFO Clean protocol
2017/07/20 21:05:19.241753 INFO WireServer endpoint is not found. Rerun dhcp handler
2017/07/20 21:05:19.242806 INFO Test for route to 168.63.129.16
2017/07/20 21:05:19.243911 INFO Route to 168.63.129.16 exists
2017/07/20 21:05:19.244699 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:05:19.252102 INFO Fabric preferred wire protocol version:2015-04-05
2017/07/20 21:05:19.253600 INFO Wire protocol version:2012-11-30
2017/07/20 21:05:19.254982 WARNING Server preferred version:2015-04-05
2017/07/20 21:05:23.855603 INFO Event: name=WALinuxAgent-2.2.14, op=HeartBeat, message=
2017/07/20 21:05:23.856421 INFO Start env monitor service.
2017/07/20 21:05:23.861285 INFO Configure routes
2017/07/20 21:05:23.863054 INFO Gateway:None
2017/07/20 21:05:23.864613 INFO Routes:None
2017/07/20 21:05:23.871269 INFO WALinuxAgent-2.2.14 running as process 8359
2017/07/20 21:05:23.873847 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:05:24.913185 INFO Wire server endpoint:168.63.129.16
2017/07/20 21:05:24.942336 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Target handler state: enabled
2017/07/20 21:05:24.945825 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] [Enable] current handler state is: enabled
2017/07/20 21:05:24.949060 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Update settings file: 0.settings
2017/07/20 21:05:24.952333 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Enable extension [bin/custom-script-shim enable]
2017/07/20 21:05:25.458023 INFO Event: name=Microsoft.Azure.Extensions.CustomScript, op=Enable, message=Launch command succeeded: bin/custom-script-shim enable
2017/07/20 21:05:25.533886 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/07/20 21:20:19.896575 INFO Agent WALinuxAgent-2.2.14 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/07/20 21:20:19.897954 INFO Event: name=WALinuxAgent, op=Enable, message=Agent WALinuxAgent-2.2.14 launched with command 'python3 -u /usr/sbin/waagent -run-exthandlers' is successfully running
2017/07/20 21:33:48.683486 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Target handler state: enabled
2017/07/20 21:33:48.686551 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] [Enable] current handler state is: enabled
2017/07/20 21:33:48.688063 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Update settings file: 0.settings
2017/07/20 21:33:48.691440 INFO [Microsoft.Azure.Extensions.CustomScript-2.0.3] Enable extension [bin/custom-script-shim enable]
2017/07/20 21:33:49.696128 INFO Event: name=Microsoft.Azure.Extensions.CustomScript, op=Enable, message=Launch command succeeded: bin/custom-script-shim enable
2017/07/20 21:33:49.730052 INFO Event: name=WALinuxAgent, op=ProcessGoalState, message=
2017/07/20 21:35:25.315015 INFO Event: name=WALinuxAgent-2.2.14, op=HeartBeat, message=
2017/07/20 22:05:26.100740 INFO Event: name=WALinuxAgent-2.2.14, op=HeartBeat, message=
2017/07/20 22:35:27.728029 INFO Event: name=WALinuxAgent-2.2.14, op=HeartBeat, message=
```
/var/lib/waagent/custom-script/download/0/stdout:
```
[CloudApiDev05] [2017-07-20 21:03:34]: 1st Loop to sleep
[CloudApiDev05] [2017-07-20 21:03:34]: Trying to sleep 30s. nRetries: 1
[CloudApiDev05] [2017-07-20 21:04:04]: Trying to sleep 30s. nRetries: 2
```

**Comment by boumenot** [comment] 2017-10-11 05:57
I cannot reproduce this issue.  

```text
cat stdout
1st Loop to sleep
Trying to sleep 30s. nRetries: 1
Trying to sleep 30s. nRetries: 2
Trying to sleep 30s. nRetries: 3
Trying to sleep 30s. nRetries: 4
Trying to sleep 30s. nRetries: 5
Trying to sleep 30s. nRetries: 6
Trying to sleep 30s. nRetries: 7
Trying to sleep 30s. nRetries: 8
Trying to sleep 30s. nRetries: 9
Trying to sleep 30s. nRetries: 10
Trying to sleep 30s. nRetries: 11
Trying to sleep 30s. nRetries: 12
Trying to sleep 30s. nRetries: 13
```

After re-reviewing your logs I think this is a dupe of #106.

**Closed by boumenot** 2017-10-11 05:57 UTC
