### ISSUE TITLE
stuck at transitioning for 1hr+

### ISSUE THREAD

**Issue by Teodelas** [Azure/custom-script-extension-linux#102] opened 2017-08-31 14:49 UTC
The CSE I'm trying to deploy is stuck at transitioning for over an hour.  I can run the script manually and it completes fine.  Also, I never find the script files downloaded.

**Comment by Teodelas** [comment] 2017-08-31 14:50
[waagent.log.txt](https://github.com
[handler.log.txt](https://github.com/Azure/custom-script-extension-linux/files/1267479/handler.log.txt)
/Azure/custom-script-extension-linux/files/1267478/waagent.log.txt)

**Comment by Teodelas** [comment] 2017-08-31 14:51
[handler.log.txt](https://github.com/Azure/custom-script-extension-linux/files/1267483/handler.log.txt)

**Comment by Teodelas** [comment] 2017-08-31 14:51
[waagent.log.txt](https://github.com/Azure/custom-script-extension-linux/files/1267485/waagent.log.txt)

**Comment by boumenot** [comment] 2017-08-31 15:25
Thank you for opening an issue.  

It looks like this is a dupe of an issue I logged against the Guest Agent, see [749](https://github.com/Azure/WALinuxAgent/issues/749).  The agent upgraded while the extension was running, but the way this extension works is by forking into the background to work around timeout limitations in the agent.  

The agent team will not (and cannot) make a fix because the extension violates the contract.  The extension violates the contract because a timeout of five minutes is not an acceptable amount of time in some cases for custom script to execute.

 1. When does your script run?  As part of deployment, or at some other time?  You may be able to use custom data instead of CustomScript to execute your script at provisioning time.
 1. How long does it take for your script to execute?  I can consider introducing a feature to not double-fork, and thereby prevent these types of issues.

**Comment by boumenot** [comment] 2017-09-05 16:55
We traced this down to a yum update call, but we did not root cause if the yum command required a console and was failing or something else entirely.

**Closed by boumenot** 2017-09-05 16:55 UTC
